robocopy \\sistel8207\c$\Dokeo\ \\central_1\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_2\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_3\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_4\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_5\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_6\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_7\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_8\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_9\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_10\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_11\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_12\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_13\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_14\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_15\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_16\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"
robocopy \\sistel8207\c$\Dokeo\ \\central_17\c$\Dokeo\ /MIR /log:"D:\TEMP\log_robocopy.txt"

pause